"""add phone number

Revision ID: 636a18f01a00
Revises: d417d063cea3
Create Date: 2022-10-20 09:48:28.234759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636a18f01a00'
down_revision = 'd417d063cea3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
